export { default as Navbar} from "./Navbar";
export { default as Footer } from "./Footer";
export { default as HomePage } from "./HomePage";
export {default as Events} from "./Events";
export { default as FeaturedEvents } from "./FeaturedEvents";
export { default as UpcomingEvents} from "./UpcomingEvents";
export { default as CreateEvent } from "./CreateEvent";
export { default as Login} from "./Login";
export { default as Newsletter } from "./Newsletter";
export { default as UserReviews} from "./UserReviews";